// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebMoney.Data;

#nullable disable

namespace WebMoney.Data.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20260421163532_Init1")]
    partial class Init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebMoney.Data.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<string>("CardStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("card_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency_code");

                    b.Property<string>("HashedPinCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_pin_code");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<DateOnly>("PeriodOfValidity")
                        .HasColumnType("date")
                        .HasColumnName("period_of_validity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("WebMoney.Data.Entities.CardLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("DailyLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("daily_limit");

                    b.Property<decimal?>("MonthlyLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_limit");

                    b.Property<decimal?>("PerOperationLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("per_operation_limit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_card_limits");

                    b.ToTable("card_limits", (string)null);
                });

            modelBuilder.Entity("WebMoney.Data.Entities.CardUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<int?>("CardLimitId")
                        .HasColumnType("integer")
                        .HasColumnName("card_limit_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_card_user_profiles");

                    b.HasIndex("CardLimitId")
                        .HasDatabaseName("ix_card_user_profiles_card_limit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_card_user_profiles_user_id");

                    b.HasIndex("CardId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_card_user_profiles_card_id_user_id");

                    b.ToTable("card_user_profiles", (string)null);
                });

            modelBuilder.Entity("WebMoney.Data.Entities.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_counterparties");

                    b.ToTable("counterparties", (string)null);
                });

            modelBuilder.Entity("WebMoney.Data.Entities.IdentityDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentIDNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_id_number");

                    b.Property<string>("DocumentPhotoLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_photo_link");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_identity_documents");

                    b.ToTable("identity_documents", (string)null);
                });

            modelBuilder.Entity("WebMoney.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<int>("CounterpartyId")
                        .HasColumnType("integer")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transaction_status");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_transactions_card_id");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("ix_transactions_counterparty_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("WebMoney.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebMoney.Data.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("IdentityDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("identity_document_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_users_profiles");

                    b.HasIndex("IdentityDocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_profiles_identity_document_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_profiles_user_id");

                    b.ToTable("users_profiles", (string)null);
                });

            modelBuilder.Entity("WebMoney.Data.Entities.CardUserProfile", b =>
                {
                    b.HasOne("WebMoney.Data.Entities.Card", "Card")
                        .WithMany("CardUserProfiles")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_user_profiles_cards_card_id");

                    b.HasOne("WebMoney.Data.Entities.CardLimit", "CardLimit")
                        .WithMany("CardUserProfiles")
                        .HasForeignKey("CardLimitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_card_user_profiles_card_limits_card_limit_id");

                    b.HasOne("WebMoney.Data.Entities.User", "User")
                        .WithMany("CardUserProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_user_profiles_users_user_id");

                    b.Navigation("Card");

                    b.Navigation("CardLimit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebMoney.Data.Entities.Transaction", b =>
                {
                    b.HasOne("WebMoney.Data.Entities.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_cards_card_id");

                    b.HasOne("WebMoney.Data.Entities.Counterparty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_counterparties_counterparty_id");

                    b.Navigation("Card");

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("WebMoney.Data.Entities.UserProfile", b =>
                {
                    b.HasOne("WebMoney.Data.Entities.IdentityDocument", "IdentityDocument")
                        .WithOne("UserProfile")
                        .HasForeignKey("WebMoney.Data.Entities.UserProfile", "IdentityDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_profiles_identity_documents_identity_document_id");

                    b.HasOne("WebMoney.Data.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("WebMoney.Data.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_profiles_users_user_id");

                    b.Navigation("IdentityDocument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebMoney.Data.Entities.Card", b =>
                {
                    b.Navigation("CardUserProfiles");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WebMoney.Data.Entities.CardLimit", b =>
                {
                    b.Navigation("CardUserProfiles");
                });

            modelBuilder.Entity("WebMoney.Data.Entities.IdentityDocument", b =>
                {
                    b.Navigation("UserProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("WebMoney.Data.Entities.User", b =>
                {
                    b.Navigation("CardUserProfiles");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
